version: '3'
services:
  chrome:
    image: selenium/node-chrome:4.1.0-prerelease-20211105
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge:
    image: selenium/node-edge:4.1.0-prerelease-20211105
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
  firefox:
    image: selenium/node-firefox:4.1.0-prerelease-20211105
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
  selenium-hub:
    image: selenium/hub:4.1.0-prerelease-20211105
    container_name: selenium-hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
  search-module1:
    image: dsugawara/selenium-docker
    depends_on:
      - chrome
      - firefox
      - edge
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result1:/usr/share/udemy/test-output
  search-module2:
    image: dsugawara/selenium-docker
    depends_on:
      - chrome
      - firefox
      - edge
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result2:/usr/share/udemy/test-output
  book-flight-module1:
    image: dsugawara/selenium-docker
    depends_on:
      - chrome
      - firefox
      - edge
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result1:/usr/share/udemy/test-output
  book-flight-module2:
    image: dsugawara/selenium-docker
    depends_on:
      - chrome
      - firefox
      - edge
    environment:
      - BROWSER=firefox
      - HUB_HOST=selenium-hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result2:/usr/share/udemy/test-output
